[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"
solc_version = "0.8.30"
libs = ["node_modules"]
remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "forge-std/=node_modules/forge-std/src/",
]

[rpc_endpoints]
arc_testnet = "${ARC_TESTNET_RPC_URL}"

[invariant]
runs = 80
depth = 20