"use client";

import { useState } from "react";
import { ARC_TESTNET, OrderStatus, getExplorerTransactionUrl, type PaymentIntentView } from "@settle/shared";
import { connectWallet, submitBuyerTransaction, switchToArcTestnet, type Eip1193Provider, type WalletState } from "../lib/buyer-wallet-adapter";
import type { BuyerOrderResponse, JsonIntent } from "../lib/buyer-order-intent-service";
import type { BuyerConfirmationResponse } from "../lib/buyer-transaction-confirmation";
import { composeBuyerOperationState, projectOrderActionState } from "../lib/order-action-state";
import { createBuyerOperation, projectBuyerOperation, restoreBuyerOperation, transitionBuyerOperation, type BuyerOperationRecord } from "../lib/buyer-transaction-progress";
import { clearBuyerOperationRecovery, readBuyerOperationRecovery, recoveryFromOperation, writeBuyerOperationRecovery } from "../lib/buyer-operation-recovery-storage";

declare global { interface Window { ethereum?: Eip1193Provider } }
type PaymentOperation = "approve" | "fund";
const executableIntent = (intent: JsonIntent) => ({ ...intent, value: 0n }) as never;

export function BuyerPaymentFlow({ paymentIntent }: { paymentIntent: PaymentIntentView }) {
  const [wallet, setWallet] = useState<WalletState>({ account: null, chainId: null });
  const [order, setOrder] = useState<BuyerOrderResponse | null>(null);
  const [approve, setApprove] = useState(() => createBuyerOperation(paymentIntent.orderId, "approve"));
  const [fund, setFund] = useState(() => createBuyerOperation(paymentIntent.orderId, "fund"));
  const [message, setMessage] = useState("");
  const [checking, setChecking] = useState(false);
  const provider = () => { if (!window.ethereum) throw new Error("No injected EVM wallet found"); return window.ethereum; };
  const active = fund.progress !== "idle" ? fund : approve;
  const operationState = projectBuyerOperation(active);
  const onRequiredNetwork = wallet.chainId === ARC_TESTNET.chainId;
  const actionState = order ? composeBuyerOperationState(projectOrderActionState({ status: Number(order.status), buyer: order.buyer, connectedAccount: wallet.account, fundingDeadlineOpen: order.fundingDeadlineOpen, fundingDeadlineExpired: order.fundingDeadlineExpired, allowance: BigInt(order.allowance.baseUnits), requiredAmount: BigInt(order.amount.baseUnits) }), operationState) : null;

  function pair(operation: PaymentOperation): [BuyerOperationRecord, (value: BuyerOperationRecord) => void] { return operation === "approve" ? [approve, setApprove] : [fund, setFund]; }
  function persist(record: BuyerOperationRecord) { const recovery = recoveryFromOperation(record); if (recovery) writeBuyerOperationRecovery(recovery); else if (["state-confirmed", "reverted"].includes(record.progress)) clearBuyerOperationRecovery(record.orderId, record.operation); }
  async function readOrder(account: string | null): Promise<BuyerOrderResponse> { const response = await fetch("/api/buyer/order", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ orderId: paymentIntent.orderId, callerAddress: account }) }); const body = await response.json() as BuyerOrderResponse | { error?: { message?: string } }; if (!response.ok) throw new Error("error" in body ? body.error?.message : "Unable to load checkout"); return body as BuyerOrderResponse; }
  function reconcile(next: BuyerOrderResponse) { setOrder(next); if (next.status !== String(OrderStatus.Created)) { clearBuyerOperationRecovery(paymentIntent.orderId, "approve"); clearBuyerOperationRecovery(paymentIntent.orderId, "fund"); setApprove(createBuyerOperation(paymentIntent.orderId, "approve")); setFund(createBuyerOperation(paymentIntent.orderId, "fund")); } }
  async function connect() { setMessage(""); try { const nextWallet = await connectWallet(provider()); setWallet(nextWallet); const next = await readOrder(nextWallet.account); reconcile(next); const approvalDone = BigInt(next.allowance.baseUnits) >= BigInt(next.amount.baseUnits); const storedApprove = readBuyerOperationRecovery(paymentIntent.orderId, "approve"); const storedFund = readBuyerOperationRecovery(paymentIntent.orderId, "fund"); setApprove(approvalDone || !storedApprove ? createBuyerOperation(paymentIntent.orderId, "approve") : restoreBuyerOperation(storedApprove.orderId, storedApprove.operation, storedApprove.transactionHash, storedApprove.progress)); setFund(storedFund ? restoreBuyerOperation(storedFund.orderId, storedFund.operation, storedFund.transactionHash, storedFund.progress) : createBuyerOperation(paymentIntent.orderId, "fund")); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Wallet connection failed"); } }
  async function confirm(operation: PaymentOperation, hash: string, initial: BuyerOperationRecord) { let current = initial.progress === "confirmation-error" ? transitionBuyerOperation(initial, { type: "retry-confirmation" }) : initial; setChecking(true); try { for (let attempt = 0; attempt < 6; attempt += 1) { const response = await fetch("/api/buyer/transaction/confirm", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ orderId: paymentIntent.orderId, transactionHash: hash, operation: operation === "approve" ? "approve-usdc" : "fund-order" }) }); const body = await response.json() as BuyerConfirmationResponse; if (!response.ok) { if (current.progress === "pending-receipt" || current.progress === "included-awaiting-state") current = transitionBuyerOperation(current, { type: "confirmation-failed" }); pair(operation)[1](current); persist(current); throw new Error("Transaction exists. Check its canonical state before trying again."); } if (body.confirmationStatus === "reverted" && current.progress === "pending-receipt") current = transitionBuyerOperation(current, { type: "receipt-reverted" }); if (body.confirmationStatus === "included-awaiting-state" && current.progress === "pending-receipt") current = transitionBuyerOperation(current, { type: "receipt-included" }); if (body.confirmationStatus === "state-confirmed") { if (current.progress === "pending-receipt") current = transitionBuyerOperation(current, { type: "receipt-included" }); if (current.progress === "included-awaiting-state") current = transitionBuyerOperation(current, { type: "canonical-state-confirmed" }); pair(operation)[1](current); persist(current); reconcile(await readOrder(wallet.account)); return; } pair(operation)[1](current); persist(current); if (body.confirmationStatus === "reverted") return; await new Promise((resolve) => setTimeout(resolve, 2_000)); } } finally { setChecking(false); } }
  async function submit(operation: PaymentOperation, intent: JsonIntent) { setMessage(""); const [base, setter] = pair(operation); const submitting = transitionBuyerOperation(base, { type: "start-submit" }); setter(submitting); let submitted = false; try { const result = await submitBuyerTransaction(executableIntent(intent), provider()); const pending = transitionBuyerOperation(submitting, { type: "submission-returned-hash", transactionHash: result.hash }); setter(pending); persist(pending); submitted = true; await confirm(operation, result.hash, pending); } catch (cause) { if (!submitted) setter(transitionBuyerOperation(submitting, { type: "submission-failed" })); setMessage(cause instanceof Error ? cause.message : "Submission failed. No automatic retry was attempted."); } }

  if (!paymentIntent.checkout.paymentActionAvailable) return <p>{statusMessage(paymentIntent)}</p>;
  return <section><h2>Pay with USDC</h2>{!wallet.account && <button onClick={connect}>Connect wallet</button>}{wallet.account && <><dl><dt>Connected wallet</dt><dd>{wallet.account}</dd></dl>{!onRequiredNetwork && <button className="secondary" onClick={async () => { await switchToArcTestnet(provider()); await connect(); }}>Switch to Arc Testnet</button>}{actionState?.connectedRole === "other" && <p className="warning">This checkout is assigned to another wallet.</p>}{actionState?.connectedRole === "buyer" && actionState.primaryBuyerAction === "approve" && order?.approveIntent && <button disabled={!onRequiredNetwork || !actionState.approve.available || !projectBuyerOperation(approve).submitAllowed} onClick={() => submit("approve", order.approveIntent!)}>Approve {paymentIntent.amount.usdc} USDC</button>}{actionState?.connectedRole === "buyer" && actionState.primaryBuyerAction === "fund" && order?.fundIntent && <button disabled={!onRequiredNetwork || !actionState.fund.available || !projectBuyerOperation(fund).submitAllowed} onClick={() => submit("fund", order.fundIntent!)}>Pay {paymentIntent.amount.usdc} USDC</button>}</>}{active.progress !== "idle" && <div><p><strong>{operationState.statusLabel}</strong> — {operationState.statusMessage}</p>{operationState.transactionHash && <a href={getExplorerTransactionUrl(operationState.transactionHash)} target="_blank" rel="noreferrer">View transaction on ArcScan</a>}<p>A hash or successful receipt alone is not payment confirmation.</p>{operationState.recovery === "confirm-existing" && <button className="secondary" disabled={checking} onClick={() => confirm(active.operation as PaymentOperation, active.transactionHash!, active)}>{checking ? "Checking…" : "Check existing transaction"}</button>}</div>}{message && <p className="error" role="alert">{message}</p>}</section>;
}

function statusMessage(intent: PaymentIntentView): string {
  if (intent.paymentState === "payment-window-expired") return "Payment window expired. This unfunded order can no longer be paid.";
  if (intent.paymentState === "funded") return "Payment funded. USDC is held in escrow; settlement is not yet complete.";
  if (intent.paymentState === "disputed") return "Payment is held in escrow. A dispute is active and arbitrator resolution is required.";
  if (intent.paymentState === "completed") return "Settlement completed.";
  if (intent.paymentState === "refunded") return "Refunded. The full escrowed amount was returned to the buyer.";
  if (intent.paymentState === "cancelled") return "Cancelled. This unfunded order cancellation is not a refund.";
  return "Payment is not available.";
}